// AUTO-GENERATED by scripts/generate-next-pages.mjs — do not edit.
"use client";

import dynamic from "next/dynamic";

const Screen = dynamic(() => import("@/screens/(features)/marketplace/myListings"), { ssr: false });

export default function Page() {
  return <Screen />;
}
