// AUTO-GENERATED by scripts/generate-next-pages.mjs — do not edit.
"use client";

import type { ReactNode } from "react";
import dynamic from "next/dynamic";
import { RouteContentProvider } from "expo-router";

const Layout = dynamic(() => import("@/screens/auth/_layout"), { ssr: false });

export default function GeneratedLayout({ children }: { children: ReactNode }) {
  return (
    <RouteContentProvider value={children}>
      <Layout />
    </RouteContentProvider>
  );
}
