// AUTO-GENERATED by scripts/generate-next-pages.mjs — do not edit.
import type { Metadata, Viewport } from "next";
import type { ReactNode } from "react";
import RootShell from "@/shims/next-root-shell";
import "../global.css";

export const metadata: Metadata = {
  title: "3names",
  description: "3names — campus social, study and games",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RootShell>{children}</RootShell>
      </body>
    </html>
  );
}
