// hooks/useGiftThumbnail.ts
//
// Shared helper for showing a gift's video thumbnail. Reads the thumbnail
// from the local cache (store/giftStore) and, if it hasn't been generated
// yet, generates it from the gift's video once and caches it — so the same
// image is reused across the grid tiles, the send button, etc.
//
// Returns `{ uri, loading }` so callers can show a spinner while the
// thumbnail is being generated and fall back to the emoji icon only when a
// gift has no video (or generation failed).

import { useEffect, useState } from "react";
import * as VideoThumbnails from "expo-video-thumbnails";
import { useGiftStore } from "@/store/giftStore";

export interface GiftThumbnailResult {
  uri: string | undefined;
  loading: boolean;
}

/**
 * Returns the video thumbnail URI for a gift (keyed by videoUrl), or
 * generates + caches it on first use. `loading` is true while the
 * thumbnail is being generated; `uri` is undefined for gifts without a
 * video or when generation fails.
 */
export function useGiftThumbnail(
  videoUrl?: string | null,
): GiftThumbnailResult {
  const thumbnails = useGiftStore((state) => state.thumbnails);
  const setThumbnail = useGiftStore((state) => state.setThumbnail);

  const cached = videoUrl ? thumbnails[videoUrl] : undefined;
  const [localUri, setLocalUri] = useState<string | undefined>(cached);
  const [loading, setLoading] = useState<boolean>(
    Boolean(videoUrl && !cached),
  );

  useEffect(() => {
    // Reset whenever the video changes so we never show the previous
    // gift's thumbnail while the new one is being generated.
    setLocalUri(undefined);
    setLoading(false);

    if (!videoUrl) return;

    // Already cached (possibly generated by another tile) — just adopt it.
    if (cached) {
      setLocalUri(cached);
      return;
    }

    setLoading(true);
    let mounted = true;
    VideoThumbnails.getThumbnailAsync(videoUrl, { time: 100, quality: 0.5 })
      .then(({ uri }) => {
        if (!mounted) return;
        setLocalUri(uri);
        setLoading(false);
        setThumbnail(videoUrl, uri);
      })
      .catch(() => {
        // Fall back to the emoji icon when thumbnail generation fails.
        if (mounted) setLoading(false);
      });

    return () => {
      mounted = false;
    };
  }, [videoUrl, cached, setThumbnail]);

  return { uri: localUri ?? cached, loading };
}
